# templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    app: {{ .Values.appLabel }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.appLabel }}
    spec:
      containers:
        - name: {{ .Values.container.name }}
          image: {{ .Values.image.repo }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.container.port }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
